# Chapter-9 Standard Libraries
This notebook contains the sample source code explained in the book *Hands-On Julia Programming, Sambit Kumar Dash, 2021, bpb Publications. All Rights Reserved*.

In [367]:
using Pkg
pkg"activate ."
pkg"instantiate"

  Activating environment at `C:\Users\vishn\Hands-on-Julia-Programming\Chapter 09\Project.toml`
  Activating environment at `C:\Users\vishn\Hands-on-Julia-Programming\Chapter 09\Project.toml`


Step: 4
Step: 4
Step: 24
Step: 24


## 9.1 Introduction

There are various functions and methods that are part of Julia already. A developer needs to use them directly rather than having to code for them. This chapter is a bird's eyeview of such methods. 

### Modules

Namespaces where a method or a type reside. Using a method or type outside the module may require explicit qualification. 

In [368]:
module m1
    function f()
        println("Defined as m1.f")
    end
    function g()
        println("Defined as m1.g")
    end
    function h()
        println("Defined as m1.h")
    end
    export f
end

module m2
    function f()
        println("Defined as m2.f")
    end
    function g()
        println("Defined as m2.g")
    end
    export g
end

Main.m2

Main.m2

In [369]:
names(m1)

2-element Vector{Symbol}:
 :f
 :m1

2-element Vector{Symbol}:
 :f
 :m1

In [370]:
names(m2)

2-element Vector{Symbol}:
 :g
 :m2

2-element Vector{Symbol}:
 :g
 :m2

In [371]:
f()

Defined as m1.f
Defined as m1.f


In [372]:
m1.f()

Defined as m1.f
Defined as m1.f


In [373]:
m2.f()

Defined as m2.f
Defined as m2.f


In [374]:
using .m1

In [375]:
f()

Defined as m1.f
Defined as m1.f


In [376]:
g()

Defined as m2.g
Defined as m2.g


In [377]:
using Main.m2

In [378]:
g()

Defined as m2.g
Defined as m2.g


In [379]:
using .m1: g

In [380]:
g()

Defined as m2.g
Defined as m2.g


In [381]:
using .m1: h

In [382]:
h()

Defined as m1.h
Defined as m1.h


## 9.2 Standard Modules

`Core`, `Base` and `Main` the bare minimum modules of a Julia shell. `m1` and `m2` here are submodules of `Main`.

In [383]:
varinfo()

| name    |       size | summary                     |
|:------- | ----------:|:--------------------------- |
| A       |  136 bytes | 3×4 Matrix{Float64}         |
| A2      |    0 bytes | Nothing                     |
| Base    |            | Module                      |
| Core    |            | Module                      |
| Main    |            | Module                      |
| c       | 64.299 KiB | TCPSocket                   |
| d       |    8 bytes | Date                        |
| data    |  1.602 KiB | 100×2 Matrix{Float64}       |
| fd      |  335 bytes | IOStream                    |
| fs      |   96 bytes | Base.Filesystem.StatStruct  |
| header  |  1.180 KiB | 1×2 Matrix{AbstractString}  |
| io      |   88 bytes | IOBuffer                    |
| m1      |  5.719 KiB | Module                      |
| m2      |  4.846 KiB | Module                      |
| nc      |    8 bytes | Int64                       |
| nr      |    8 bytes | Int64                       |
| old_dir |   60 bytes | 52-codeunit String          |
| p       |   96 bytes | Dates.CompoundPeriod        |
| str     |   38 bytes | 30-codeunit String          |
| t       |    8 bytes | DateTime                    |
| x       |  840 bytes | 100-element Vector{Int64}   |
| y       |  840 bytes | 100-element Vector{Float64} |


| name    |       size | summary                     |
|:------- | ----------:|:--------------------------- |
| A       |  136 bytes | 3×4 Matrix{Float64}         |
| A2      |    0 bytes | Nothing                     |
| Base    |            | Module                      |
| Core    |            | Module                      |
| Main    |            | Module                      |
| c       | 64.299 KiB | TCPSocket                   |
| d       |    8 bytes | Date                        |
| data    |  1.602 KiB | 100×2 Matrix{Float64}       |
| fd      |  335 bytes | IOStream                    |
| fs      |   96 bytes | Base.Filesystem.StatStruct  |
| header  |  1.180 KiB | 1×2 Matrix{AbstractString}  |
| io      |   88 bytes | IOBuffer                    |
| m1      |  5.719 KiB | Module                      |
| m2      |  4.846 KiB | Module                      |
| nc      |    8 bytes | Int64                       |
| nr      |    8 bytes | Int64                       |
| old_dir |   60 bytes | 52-codeunit String          |
| p       |   96 bytes | Dates.CompoundPeriod        |
| str     |   38 bytes | 30-codeunit String          |
| t       |    8 bytes | DateTime                    |
| x       |  840 bytes | 100-element Vector{Int64}   |
| y       |  840 bytes | 100-element Vector{Float64} |


In [384]:
x = 1

1

1

In [385]:
varinfo()

| name    |       size | summary                     |
|:------- | ----------:|:--------------------------- |
| A       |  136 bytes | 3×4 Matrix{Float64}         |
| A2      |    0 bytes | Nothing                     |
| Base    |            | Module                      |
| Core    |            | Module                      |
| Main    |            | Module                      |
| c       | 64.299 KiB | TCPSocket                   |
| d       |    8 bytes | Date                        |
| data    |  1.602 KiB | 100×2 Matrix{Float64}       |
| fd      |  335 bytes | IOStream                    |
| fs      |   96 bytes | Base.Filesystem.StatStruct  |
| header  |  1.180 KiB | 1×2 Matrix{AbstractString}  |
| io      |   88 bytes | IOBuffer                    |
| m1      |  5.719 KiB | Module                      |
| m2      |  4.846 KiB | Module                      |
| nc      |    8 bytes | Int64                       |
| nr      |    8 bytes | Int64                       |
| old_dir |   60 bytes | 52-codeunit String          |
| p       |   96 bytes | Dates.CompoundPeriod        |
| str     |   38 bytes | 30-codeunit String          |
| t       |    8 bytes | DateTime                    |
| x       |    8 bytes | Int64                       |
| y       |  840 bytes | 100-element Vector{Float64} |


| name    |       size | summary                     |
|:------- | ----------:|:--------------------------- |
| A       |  136 bytes | 3×4 Matrix{Float64}         |
| A2      |    0 bytes | Nothing                     |
| Base    |            | Module                      |
| Core    |            | Module                      |
| Main    |            | Module                      |
| c       | 64.299 KiB | TCPSocket                   |
| d       |    8 bytes | Date                        |
| data    |  1.602 KiB | 100×2 Matrix{Float64}       |
| fd      |  335 bytes | IOStream                    |
| fs      |   96 bytes | Base.Filesystem.StatStruct  |
| header  |  1.180 KiB | 1×2 Matrix{AbstractString}  |
| io      |   88 bytes | IOBuffer                    |
| m1      |  5.719 KiB | Module                      |
| m2      |  4.846 KiB | Module                      |
| nc      |    8 bytes | Int64                       |
| nr      |    8 bytes | Int64                       |
| old_dir |   60 bytes | 52-codeunit String          |
| p       |   96 bytes | Dates.CompoundPeriod        |
| str     |   38 bytes | 30-codeunit String          |
| t       |    8 bytes | DateTime                    |
| x       |    8 bytes | Int64                       |
| y       |  840 bytes | 100-element Vector{Float64} |


## 9.3 System

The submodule that interacts with the operating system. System command execution being one of them. 

In [386]:
run(`cmd /c dir`)

 Volume in drive C is OS
 Volume Serial Number is 244C-B574

 Directory of C:\Users\vishn\Hands-on-Julia-Programming\Chapter 09

01-10-2022  23:04    <DIR>          .
01-10-2022  23:04    <DIR>          ..
01-10-2022  22:58    <DIR>          .ipynb_checkpoints
01-10-2022  23:02            29,020 Chapter-9 Standard Libraries.ipynb
01-10-2022  23:04         6,949,901 julia-1.5.3.tar.gz
01-10-2022  23:02             5,151 Manifest.toml
01-10-2022  23:02                55 Project.toml
               4 File(s)      6,984,127 bytes
               3 Dir(s)  49,685,606,400 bytes free


Process(`cmd /c dir`, ProcessExited(0))

 Volume in drive C is OS
 Volume Serial Number is 244C-B574

 Directory of C:\Users\vishn\Hands-on-Julia-Programming\Chapter 09

01-10-2022  23:04    <DIR>          .
01-10-2022  23:04    <DIR>          ..
01-10-2022  22:58    <DIR>          .ipynb_checkpoints
01-10-2022  23:02            29,020 Chapter-9 Standard Libraries.ipynb
01-10-2022  23:04         6,949,901 julia-1.5.3.tar.gz
01-10-2022  23:02             5,151 Manifest.toml
01-10-2022  23:02                55 Project.toml
               4 File(s)      6,984,127 bytes
               3 Dir(s)  49,685,606,400 bytes free


Process(`cmd /c dir`, ProcessExited(0))

In [387]:
Sys.isunix(), Sys.iswindows()

(false, true)

(false, true)

## 9.4 Filesystem

File organization and manipulation (not read and write). 

In [388]:
old_dir = pwd()

"C:\\Users\\vishn\\Hands-on-Julia-Programming\\Chapter 09"

"C:\\Users\\vishn\\Hands-on-Julia-Programming\\Chapter 09"

In [389]:
cd("..")

In [390]:
pwd()

"C:\\Users\\vishn\\Hands-on-Julia-Programming"

"C:\\Users\\vishn\\Hands-on-Julia-Programming"

In [391]:
cd(old_dir)

In [392]:
pwd()

"C:\\Users\\vishn\\Hands-on-Julia-Programming\\Chapter 09"

"C:\\Users\\vishn\\Hands-on-Julia-Programming\\Chapter 09"

In [393]:
cd(".."); pwd()

"C:\\Users\\vishn\\Hands-on-Julia-Programming"

"C:\\Users\\vishn\\Hands-on-Julia-Programming"

In [394]:
readdir()  #Same as readdir(pwd())

20-element Vector{String}:
 ".DS_Store"
 ".git"
 "Chapter 02"
 "Chapter 03"
 "Chapter 04"
 "Chapter 05"
 "Chapter 06"
 "Chapter 07"
 "Chapter 08"
 "Chapter 09"
 "Chapter 10"
 "Chapter 11"
 "Chapter 12"
 "Chapter 13"
 "Chapter 14"
 "Chapter 15"
 "Chapter 16"
 "Chapter 17"
 "LICENSE"
 "README.md"

20-element Vector{String}:
 ".DS_Store"
 ".git"
 "Chapter 02"
 "Chapter 03"
 "Chapter 04"
 "Chapter 05"
 "Chapter 06"
 "Chapter 07"
 "Chapter 08"
 "Chapter 09"
 "Chapter 10"
 "Chapter 11"
 "Chapter 12"
 "Chapter 13"
 "Chapter 14"
 "Chapter 15"
 "Chapter 16"
 "Chapter 17"
 "LICENSE"
 "README.md"

In [395]:
for (root, dirs, files) in walkdir("Chapter-09")
    println("Directories in $root")
    for dir in dirs
        println(joinpath(root, dir)) # path to directories
    end
    println("Files in $root")
    for file in files
        println(joinpath(root, file)) # path to files
    end
end

LoadError: IOError: readdir("Chapter-09"): no such file or directory (ENOENT)

LoadError: IOError: readdir("Chapter-09"): no such file or directory (ENOENT)

In [396]:
cd(old_dir); pwd()

"C:\\Users\\vishn\\Hands-on-Julia-Programming\\Chapter 09"

"C:\\Users\\vishn\\Hands-on-Julia-Programming\\Chapter 09"

In [397]:
fs = stat("Chapter-9 Standard Libraries.ipynb")

StatStruct(mode=0o100666, size=29020)

StatStruct(mode=0o100666, size=29020)

## 9.5 Parallel Programming

Execution of programs in tandem in various execution environments, yet be able to obtain meaningful and synchronized results. Performance and resource utilization are two major outcomes of this kind of programming. 

### Asynchronous Programming

Breaking the code into small chunks of executable pieces that can be executed in parallel. Depending on the kind of processing permitted by the hardware and OS, these may run in one execution thread or multiple.

#### Tasks

In [398]:
t = Task() do 
    sleep(10)
    println("done")
end

Task (runnable) @0x000000000eb7ce20

Task (runnable) @0x000000000eb7ce20

In [399]:
schedule(t)

Task (runnable) @0x000000000eb7ce20

Task (runnable) @0x000000000eb7ce20

In [400]:
t = Task() do 
    sleep(10)
    println("done")
end

Task (runnable) @0x000000000eb7d780

Task (runnable) @0x000000000eb7d780

In [401]:
schedule(t); wait(t)

Step: 68
Step: 68
Step: 5
Step: 25
Step: 5
Step: 25
Step: 69
Step: 69
Step: 6
Step: 6
Step: 26
Step: 26
Step: 70
Step: 70
Step: 7
Step: 27
Step: 7
Step: 27
Step: 71
Step: 71
Step: 8
Step: 28
Step: 8
Step: 28
Step: 72
Step: 72
Step: 9
Step: 29
Step: 9
Step: 29
Step: 73
Step: 73
Step: 10
Step: 30
Step: 10
Step: 30
Step: 74
Step: 74
Step: 11
Step: 31
Step: 11
Step: 31
Step: 75
Step: 75
Step: 12
Step: 32
Step: 12
Step: 32
Step: 76
Step: 76
Step: 13
Step: 33
Step: 13
Step: 33
Step: 77
Step: 77
Step: 14
Step: 34
Step: 14
Step: 34
done
done
done
done


In [402]:
t = @task begin
    sleep(5)
    println("done")
end

Task (runnable) @0x000000000eb7e270

Task (runnable) @0x000000000eb7e270

In [403]:
@sync  begin
    sleep(5)
    println("done")
end

Step: 78
Step: 78
Step: 15
Step: 35
Step: 15
Step: 35
Step: 79
Step: 79
Step: 16
Step: 16
Step: 36
Step: 36
Step: 80
Step: 80
Step: 17
Step: 37
Step: 17
Step: 37
Step: 81
Step: 81
Step: 18
Step: 38
Step: 18
Step: 38
Step: 82
Step: 82
Step: 19
Step: 19
Step: 39
Step: 39
done
done


#### Channels

In [404]:
c = Channel(8)

Channel{Any}(8) (empty)

Channel{Any}(8) (empty)

In [405]:
c = Channel{Int}(4)

Channel{Int64}(4) (empty)

Channel{Int64}(4) (empty)

In [406]:
@async begin
    for i = 1:100
        println("Adding $i to channel")
        put!(c, i)
    end
end

@async begin
    for i = 1:100
        v = take!(c)
        println("Removing value: $v")
    end
end

Task (runnable) @0x000000000eb7e590

Task (runnable) @0x000000000eb7e590

Adding 1 to channel
Adding 1 to channel


In [407]:
close(c)

Adding 2 to channel
Adding 3 to channel
Removing value: 1
Removing value: 2
Adding 2 to channel
Adding 3 to channel
Removing value: 1
Removing value: 2


### Multithreading

Julia can be made to run on a multiple threads mode. In such a conditions the tasks can be parallelized on these threads. Synchronization objects can be used across the executing threads. 

In [408]:
Threads.nthreads()

Step: 83


1

Step: 83


1

In [409]:
Threads.@spawn for i=1:100
    sleep(1)
    println("Step: $i")
end

Task (runnable) @0x000000000f650e20

Task (runnable) @0x000000000f650e20

### Distributed Computing

This is cluster computing infrastrcuture, where a cluster can be configured across Julia processes in the same machine or in another machine. These independent processes can execute independently yet be able to share data, pass messages and communicate over a shared channel. 

## 9.6 IO and Network

Julia accesses input and output devices as streams. The network devices are also interfaced like sockets. IO is an important stream based interface to understand. 

### Default Stream

`stdin`, `stdout` and `stderr` are the standard streams for input, output and error in most processes. `stdin` integration with Jupyter is limited. All those samples may best be reviewed in a REPL console. 

In [410]:
write(stdout, "Hello World")

Hello WorldHello World

11

11

In [411]:
write(stdout, "\u2200 x \u2203 y")

∀ x ∃ y

11

∀ x ∃ y

11

### Text I/O

### Binary I/O

### File I/O

Files are also accessed as `IO` streams for both read and write operations. However, the `IO` streams are obtained by `open` call. Any open stream must be closed with a `close` function call. 

In [412]:
write("hello.txt", "Hello World")

11

11

In [413]:
fd = open("hello.txt", "r");
data = read(fd);

In [414]:
write(fd, "This is second line")

LoadError: ArgumentError: write failed, IOStream is not writeable

LoadError: ArgumentError: write failed, IOStream is not writeable

In [415]:
close(fd)
write(stdout, data)

Hello WorldHello World

11

11

In [416]:
open("hello.txt", "r") do fd
    data = read(fd)
    write(stdout, data)
end

Hello World

11

Hello World

11

In [417]:
write("hello.txt", "Hello World");
data = read("hello.txt");
write(stdout, data);

Hello WorldHello World

Files are opened for `read` or `write`. A file opened for reading cannot be written into.  

In [418]:
open("hello.txt", "r") do fd
    while !eof(fd)
        b = read(fd, 1)
        write(stdout, b)
    end
end
rm("hello.txt")

HHello Worldello World

### Delimited Files

Generalized command separated value (CSV) kind of files. Used extensively in spreadsheets. Also interfaced in data science applications as an easier way to share data. 

In [419]:
using DelimitedFiles
x = collect(1:100);
y = Float64.(collect(101:200));
open("values.csv", "w") do f
    println(f, "X,Y")
    writedlm(f, [x y], ',')
end

In [420]:
data, header = readdlm("values.csv", ',', header=true);

In [421]:
size(data, 1)

100

100

In [422]:
header

1×2 Matrix{AbstractString}:
 "X"  "Y"

1×2 Matrix{AbstractString}:
 "X"  "Y"

In [423]:
rm("values.csv")

### Network 

Just like files are opened with open to obtain the `IO` stream to interface, sockets are equivalent network communication end points to obtain connection streams. However, if you could use download method to provide a URL and download files. 

In [424]:
download("https://github.com/JuliaLang/julia/releases/download/v1.5.3/julia-1.5.3.tar.gz", "julia-1.5.3.tar.gz")

Step: 20
Step: 40
Step: 20
Step: 40
Step: 84
Step: 1
Step: 84
Step: 1
Step: 21
Step: 21
Step: 41
Step: 41
Step: 85
Step: 2
Step: 85
Step: 2


"julia-1.5.3.tar.gz"

"julia-1.5.3.tar.gz"

In [425]:
using Sockets
@async begin
    server = listen(3000)
    while true
        s = accept(server)
        @async while isopen(s)
            msg = readline(s, keep=true)
            write(s, "Server Response: $msg")
        end  
    end
end

Task (failed) @0x000000000d480fb0
IOError: listen: address already in use (EADDRINUSE)
Stacktrace:
 [1] uv_error
   @ .\libuv.jl:97 [inlined]
 [2] #listen#13
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Sockets\src\Sockets.jl:632 [inlined]
 [3] #listen#10
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Sockets\src\Sockets.jl:625 [inlined]
 [4] #listen#12
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Sockets\src\Sockets.jl:629 [inlined]
 [5] #listen#11
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Sockets\src\Sockets.jl:628 [inlined]
 [6] listen
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Sockets\src\Sockets.jl:628 [inlined]
 [7] macro expansion
   @ .\In[425]:3 [inlined]
 [8] (::var"#115#117")()
   @ Main .\task.jl:417

Task (failed) @0x000000000d480fb0
IOError: listen: address already in use (EADDRINUSE)
Stacktrace:
 [1] uv_error
   @ .\libuv.jl:97 [inlined]
 [2] #listen#13
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Sockets\src\Sockets.jl:632 [inlined]
 [3] #listen#10
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Sockets\src\Sockets.jl:625 [inlined]
 [4] #listen#12
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Sockets\src\Sockets.jl:629 [inlined]
 [5] #listen#11
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Sockets\src\Sockets.jl:628 [inlined]
 [6] listen
   @ C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Sockets\src\Sockets.jl:628 [inlined]
 [7] macro expansion
   @ .\In[425]:3 [inlined]
 [8] (::var"#115#117")()
   @ Main .\task.jl:417

In [426]:
c = connect(3000)
@async while isopen(c)
    println(stdout, readline(c, keep=true))
end

Task (runnable) @0x000000000d8312d0

Task (runnable) @0x000000000d8312d0

In [427]:
for i = 1:5
    println(c, "Client Msg id: $i")
end

Step: 22
Server Response: Client Msg id: 1

Step: 42
Step: 22
Server Response: Client Msg id: 1

Step: 42
Server Response: Client Msg id: 2

Server Response: Client Msg id: 3

Server Response: Client Msg id: 2

Server Response: Client Msg id: 3



In [428]:
close(c)

Server Response: Client Msg id: 4

Server Response: Client Msg id: 5


Server Response: Client Msg id: 4

Server Response: Client Msg id: 5




### Memory I/O

Strings cannot be manipulated. It may help to create a byte array for `IO` in the memory and use that for text manipulations. In the end the byte array can be converted to a String. 

In [429]:
io = IOBuffer()
println(io, "This is Line 1")
println(io, "This is Line 2")
str = String(take!(io))

"This is Line 1\nThis is Line 2\n"

"This is Line 1\nThis is Line 2\n"

In [430]:
A = fill(10, (5, 20))
A[2, 3] = 20
open("mmap.bin", "w+") do fd
    write(fd, size(A, 1))
    write(fd, size(A, 2))
    write(fd, A)
end

800

800

Memory mapping is reverse problem. A file can be mapped to memory and accessed selectively page by page. This way the whole file need not be loaded in the memory. 

In [431]:
using Mmap
fd = open("mmap.bin", "r")
nr = read(fd, Int)
nc = read(fd, Int)
A2 = Mmap.mmap(fd, Matrix{Int}, (nr, nc))
println("A2[1, 1]: ", A2[1, 1], " A2[2, 3]: ", A2[2, 3])
close(fd)

A2[1, 1]: 10 A2[2, 3]: 20
A2[1, 1]: 10 A2[2, 3]: 20


In [432]:
A2 = nothing
GC.gc()
rm("mmap.bin")

## 9.7 Constants

There are many system and Julia related constants. Mathematical constants are also defined in the standard library. 

In [433]:
VERSION

v"1.6.7"

v"1.6.7"

In [434]:
C_NULL

Ptr{Nothing} @0x0000000000000000

Ptr{Nothing} @0x0000000000000000

In [435]:
Sys.BINDIR

"C:\\Users\\vishn\\AppData\\Local\\Programs\\Julia-1.6.7\\bin"

"C:\\Users\\vishn\\AppData\\Local\\Programs\\Julia-1.6.7\\bin"

In [436]:
Sys.CPU_THREADS

4

4

In [437]:
Sys.WORD_SIZE

64

64

In [438]:
Sys.KERNEL

:NT

:NT

In [439]:
Sys.MACHINE

"x86_64-w64-mingw32"

"x86_64-w64-mingw32"

In [440]:
Sys.ARCH

:x86_64

:x86_64

In [441]:
Sys.ENV

Base.EnvDict with 57 entries:
  "=C:"                             => "C:\\Users\\vishn\\Hands-on-Julia-Progra…
  "ALLUSERSPROFILE"                 => "C:\\ProgramData"
  "APPDATA"                         => "C:\\Users\\vishn\\AppData\\Roaming"
  "COLUMNS"                         => "80"
  "COMMONPROGRAMFILES"              => "C:\\Program Files\\Common Files"
  "COMMONPROGRAMFILES(X86)"         => "C:\\Program Files (x86)\\Common Files"
  "COMMONPROGRAMW6432"              => "C:\\Program Files\\Common Files"
  "COMPUTERNAME"                    => "DESKTOP-OSNGCI7"
  "COMSPEC"                         => "C:\\Windows\\system32\\cmd.exe"
  "CONDA_DEFAULT_ENV"               => "base"
  "CONDA_EXE"                       => "C:\\Users\\vishn\\anaconda3\\Scripts\\c…
  "CONDA_PROMPT_MODIFIER"           => "(base) "
  "CONDA_PYTHON_EXE"                => "C:\\Users\\vishn\\anaconda3\\python.exe"
  "CONDA_SHLVL"                     => "1"
  "DRIVERDATA"                      => "C:\\Windows\\Syste

Base.EnvDict with 57 entries:
  "=C:"                             => "C:\\Users\\vishn\\Hands-on-Julia-Progra…
  "ALLUSERSPROFILE"                 => "C:\\ProgramData"
  "APPDATA"                         => "C:\\Users\\vishn\\AppData\\Roaming"
  "COLUMNS"                         => "80"
  "COMMONPROGRAMFILES"              => "C:\\Program Files\\Common Files"
  "COMMONPROGRAMFILES(X86)"         => "C:\\Program Files (x86)\\Common Files"
  "COMMONPROGRAMW6432"              => "C:\\Program Files\\Common Files"
  "COMPUTERNAME"                    => "DESKTOP-OSNGCI7"
  "COMSPEC"                         => "C:\\Windows\\system32\\cmd.exe"
  "CONDA_DEFAULT_ENV"               => "base"
  "CONDA_EXE"                       => "C:\\Users\\vishn\\anaconda3\\Scripts\\c…
  "CONDA_PROMPT_MODIFIER"           => "(base) "
  "CONDA_PYTHON_EXE"                => "C:\\Users\\vishn\\anaconda3\\python.exe"
  "CONDA_SHLVL"                     => "1"
  "DRIVERDATA"                      => "C:\\Windows\\Syste

In [442]:
MathConstants.pi

π = 3.1415926535897...

π = 3.1415926535897...

In [443]:
MathConstants.e

ℯ = 2.7182818284590...

ℯ = 2.7182818284590...

## 9.8 Notable Modules

Miscellaneous modules of Julia library. 

### Dates

User renderable date and time representations. In the system the date is just a continuously increasing counter from a datum. These functions make meaningful period associations and provide the correct date and time. 

In [444]:
using Dates

In [445]:
now()

2022-10-01T23:04:28.297

2022-10-01T23:04:28.297

In [446]:
DateTime(2020)

2020-01-01T00:00:00

2020-01-01T00:00:00

In [447]:
t = DateTime(2020, 10, 31, 01, 02, 03)

2020-10-31T01:02:03

2020-10-31T01:02:03

In [448]:
Date(2020)

2020-01-01

2020-01-01

In [449]:
d = Date(t)

2020-10-31

2020-10-31

In [450]:
DateTime(d)

2020-10-31T00:00:00

2020-10-31T00:00:00

In [451]:
t > d

true

true

In [452]:
DateTime(2020) < now()

true

true

In [453]:
DateTime(2020) == Date(2020)

true

true

In [454]:
p = Month(3) + Day(10) + Hour(15)

3 months, 10 days, 15 hours

3 months, 10 days, 15 hours

In [455]:
typeof(p)

Step: 86


Dates.CompoundPeriod

Step: 3
Step: 86


Dates.CompoundPeriod

Step: 3


In [456]:
now() + p

2023-01-12T14:04:28.382

2023-01-12T14:04:28.382

In [457]:
Date(now())+ Day(300)

2023-07-28

2023-07-28

In [458]:
now() - DateTime(2020)

86828668392 milliseconds

86828668392 milliseconds

In [459]:
now() - Date(2020)

LoadError: MethodError: no method matching -(::DateTime, ::Date)
Closest candidates are:
  -(::StridedArray{var"#s814", N} where {var"#s814"<:Union{Dates.CompoundPeriod, Period}, N}, ::TimeType) at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Dates\src\deprecated.jl:26
  -(::TimeType, ::Dates.CompoundPeriod) at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Dates\src\periods.jl:384
  -(::T, ::T) where T<:TimeType at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Dates\src\arithmetic.jl:9
  ...

LoadError: MethodError: no method matching -(::DateTime, ::Date)
Closest candidates are:
  -(::StridedArray{var"#s814", N} where {var"#s814"<:Union{Dates.CompoundPeriod, Period}, N}, ::TimeType) at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Dates\src\deprecated.jl:26
  -(::TimeType, ::Dates.CompoundPeriod) at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Dates\src\periods.jl:384
  -(::T, ::T) where T<:TimeType at C:\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.6\Dates\src\arithmetic.jl:9
  ...

In [460]:
Date(now()) - Date(2020)

1004 days

1004 days

In [461]:
Year(now())

2022 years

2022 years

In [462]:
Month(now())

10 months

10 months

In [463]:
Day(now())

1 day

1 day

In [464]:
Week(now())

39 weeks

39 weeks

In [465]:
year(now())

2022

2022

In [466]:
tonext(today()) do d
    dayofweek(d) == Thursday &&
    dayofweekofmonth(d) == 4 &&
    month(d) == November
end

2022-11-24

2022-11-24

### Logging

Long running processes or servers running in Julia need to provide consistent and standard log reporting. This module helps create such reports. 

In [467]:
@debug "This is a debug message $(sum(rand(100)))"

In [468]:
@info "This message is just informational"

┌ Info: This message is just informational
└ @ Main In[468]:1
┌ Info: This message is just informational
└ @ Main In[468]:1


In [469]:
@warn "This is a warning message"

┌ Warning: This is a warning message
└ @ Main In[469]:1
┌ Warning: This is a warning message
└ @ Main In[469]:1


In [470]:
@error "This is an error message"

┌ Error: This is an error message
└ @ Main In[470]:1
┌ Error: This is an error message
└ @ Main In[470]:1


In [471]:
A = ones(3, 4)
@info "A is all ones" A

┌ Info: A is all ones
│   A = [1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0]
└ @ Main In[471]:2
┌ Info: A is all ones
│   A = [1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0; 1.0 1.0 1.0 1.0]
└ @ Main In[471]:2


The `Logging` module provides interfaces to implement complete loggers. It also provides the ability to override the global logger with a different local one. 

In [472]:
using Logging

In [473]:
open("file.log", "w") do f
    with_logger(SimpleLogger(f)) do
        @info "This is my simple info log"
        @error "This is an error written to file"
        @warn "This is a warning message"
        @info "Current logger is same as global logger" current_logger() == global_logger()
    end
end
write(stdout, read("file.log"));

┌ Info: This is my simple info log
└ @ Main In[473]:3
┌ Error: This is an error written to file
└ @ Main In[473]:4
┌ Warning: This is a warning message
└ @ Main In[473]:5
┌ Info: Current logger is same as global logger
│   current_logger() == global_logger() = false
└ @ Main In[473]:6
┌ Info: This is my simple info log
└ @ Main In[473]:3
┌ Error: This is an error written to file
└ @ Main In[473]:4
┌ Warning: This is a warning message
└ @ Main In[473]:5
┌ Info: Current logger is same as global logger
│   current_logger() == global_logger() = false
└ @ Main In[473]:6


In [474]:
rm("file.log")

In [475]:
@info "Current logger is same as global logger" current_logger() == global_logger()

┌ Info: Current logger is same as global logger
│   current_logger() == global_logger() = true
└ @ Main In[475]:1
┌ Info: Current logger is same as global logger
│   current_logger() == global_logger() = true
└ @ Main In[475]:1


### Statistics

This module provides simple functions for central tendencies like mean, median and standard deviations etc. Functions for correlations and covariances are also provided. However, the treatment of statistics in thi module are highly rudimentary. 

In [476]:
using Statistics

In [477]:
mean(1:10)

5.5

5.5

In [478]:
median(1:10)

5.5

5.5

In [479]:
std(1:10)

3.0276503540974917

3.0276503540974917

In [480]:
var(1:10)

9.166666666666666

9.166666666666666

In [481]:
cor(1:10, rand(10))

0.14343894886239084

0.14343894886239084

In [482]:
cor(1:10, 11:20)

1.0

1.0

In [483]:
cov(1:10, rand(10))

-0.3445490659625374

-0.3445490659625374

### Random Numbers

Provides methods for random number generation and other permutation and combination functions. 

In [484]:
using Random

In [485]:
rand(Int, 2)

2-element Vector{Int64}:
  6569195484654450909
 -4337388908353828647

2-element Vector{Int64}:
  6569195484654450909
 -4337388908353828647

In [486]:
rand(2, 3)

2×3 Matrix{Float64}:
 0.792178  0.113476   0.826045
 0.683637  0.0874705  0.772362

2×3 Matrix{Float64}:
 0.792178  0.113476   0.826045
 0.683637  0.0874705  0.772362

In [487]:
rand!(zeros(2, 3))

2×3 Matrix{Float64}:
 0.310626   0.261244   0.459716
 0.0289169  0.0245242  0.399571

2×3 Matrix{Float64}:
 0.310626   0.261244   0.459716
 0.0289169  0.0245242  0.399571

In [488]:
rand(1:4, (2, 3))

2×3 Matrix{Int64}:
 2  1  3
 2  1  2

Step: 23
Step: 43


2×3 Matrix{Int64}:
 2  1  3
 2  1  2

Step: 23
Step: 43
Step: 87
Step: 4
Step: 87
Step: 4
Step: 24
Step: 44
Step: 24
Step: 44
Step: 88
Step: 5
Step: 88
Step: 5
Step: 25
Step: 45
Step: 25
Step: 45
Step: 89
Step: 89
Step: 6
Step: 6
Step: 26
Step: 46
Step: 26
Step: 46
Step: 90
Step: 90
Step: 7
Step: 7
Step: 27
Step: 47
Step: 27
Step: 47
Step: 91
Step: 8
Step: 91
Step: 8
Step: 28
Step: 48
Step: 28
Step: 48
Step: 92
Step: 9
Step: 92
Step: 9
Step: 29
Step: 49
Step: 29
Step: 49
Step: 93
Step: 93
Step: 10
Step: 10
Step: 30
Step: 50
Step: 30
Step: 50
Step: 94
Step: 94
Step: 11
Step: 11
Step: 31
Step: 51
Step: 31
Step: 51
Step: 95
Step: 12
Step: 95
Step: 12
Step: 32
Step: 32
Step: 52
Step: 52
Step: 96
Step: 96
Step: 13
Step: 13
Step: 33
Step: 53
Step: 33
Step: 53
Step: 97
Step: 14
Step: 97
Step: 14
Step: 34
Step: 54
Step: 34
Step: 54
Step: 98
Step: 15
Step: 98
Step: 15
Step: 35
Step: 55
Step: 35
Step: 55
Step: 99
Step: 99
Step: 16
Step: 16
Step: 36
Step: 56
Step: 36
Step: 56
Step: 100
Step: 100
Step: 17
Step: 17
Step: 37
Step: 57
St

## 9.9 Conclusion

## Exercises